/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AllocationsIndexRouteImport } from './routes/allocations/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as ProductNewRouteImport } from './routes/product/new'
import { Route as ProfessorsIndexRouteImport } from './routes/professors/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsIndexRoute = AllocationsIndexRouteImport.update({
  id: '/allocations/',
  path: '/allocations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductNewRoute = ProductNewRouteImport.update({
  id: '/product/new',
  path: '/product/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsIndexRoute = ProfessorsIndexRouteImport.update({
  id: '/professors/',
  path: '/professors/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$id': typeof ProductIdRoute
  '/product/new': typeof ProductNewRoute
  '/allocations/': typeof AllocationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/product/': typeof ProductIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$id': typeof ProductIdRoute
  '/product/new': typeof ProductNewRoute
  '/allocations': typeof AllocationsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/product': typeof ProductIndexRoute
  '/professors': typeof ProfessorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$id': typeof ProductIdRoute
  '/product/new': typeof ProductNewRoute
  '/allocations/': typeof AllocationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/product/': typeof ProductIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/product/$id'
    | '/product/new'
    | '/allocations/'
    | '/courses/'
    | '/departments/'
    | '/product/'
    | '/professors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/product/$id'
    | '/product/new'
    | '/allocations'
    | '/courses'
    | '/departments'
    | '/product'
    | '/professors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/product/$id'
    | '/product/new'
    | '/allocations/'
    | '/courses/'
    | '/departments/'
    | '/product/'
    | '/professors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductIdRoute: typeof ProductIdRoute
  ProductNewRoute: typeof ProductNewRoute
  AllocationsIndexRoute: typeof AllocationsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  ProductIndexRoute: typeof ProductIndexRoute
  ProfessorsIndexRoute: typeof ProfessorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations/': {
      id: '/allocations/'
      path: '/allocations'
      fullPath: '/allocations/'
      preLoaderRoute: typeof AllocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/new': {
      id: '/product/new'
      path: '/product/new'
      fullPath: '/product/new'
      preLoaderRoute: typeof ProductNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/': {
      id: '/professors/'
      path: '/professors'
      fullPath: '/professors/'
      preLoaderRoute: typeof ProfessorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductIdRoute: ProductIdRoute,
  ProductNewRoute: ProductNewRoute,
  AllocationsIndexRoute: AllocationsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  ProductIndexRoute: ProductIndexRoute,
  ProfessorsIndexRoute: ProfessorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
